sudo: required
language: rust

rust:
  - stable

services:
  - docker

script:
- make test-docker-env
- git clone https://github.com/torkleyy/nitric.git

cache:
    apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
    cd nitric &&
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov –coveralls-id=$TRAVIS_JOB_ID –exclude-pattern=/.cargo target/kcov target/debug/riak-*

