sudo: required
language: rust

os: linux
rust:
  - stable

services:
  - docker

before_script:
  - cargo install cargo-kcov
  - git clone https://github.com/torkleyy/nitric.git

script:
  - cargo kcov --verbose --lib --coveralls

